name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    uses: JakobMelchard/.github/.github/workflows/pages.yml@main
    permissions:
      pages: write
      id-token: write
    with:
      path: '.'
