name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # needed for lastmod from git history

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://jakob.melchard.org/
          exclude-paths: /404.html

      - name: Optimize images
        if: hashFiles('assets/**') != ''
        uses: calibreapp/image-actions@1.4.1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true

      - uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - id: deployment
        uses: actions/deploy-pages@v4
