name: Deploy

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: upload
    uses: JakobMelchard/.github/.github/workflows/reusable-pages-deploy.yml@v1
    permissions:
      pages: write
      id-token: write
